config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  validates :title, :body, presence: true

  def tag_list
    self.tags.map do |t|
      t.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").map { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.map { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :author, :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    if @article.save
      redirect_to @article, notice: "Your article was created!"
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: "Your article was updated!"
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  private

    def article_params
      params.require(:article).permit(:title, :body, :tag_list)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article

  def create
    @comment = @article.comments.build(comment_params)
    if @comment.save
      redirect_to article_path(@article), notice: "Your comment was created"
    else
      redirect_to article_path(@article), notice: "Your comment was not created"
    end

  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<div class="col-sm-4">
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title text-dark">
        <%= article.title.titleize %>
      </h5>
      <p class="card-text text-muted">
        <%= article.body.truncate(110) %>
      </p>
      <%= link_to 'Read More', article_path(article), class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="card mt-4">
  <div class="card-body">
    <%= form_with model: @article, local: true do |f| %>
      <% if @article.errors.any? %>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :tag_list %>
        <%= f.text_field :tag_list, class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row mb-3">
  <div class="col">
    <h1>Articles</h1>
  </div>
  <div class="col">
    <%= link_to 'New Article', new_article_path, class: "btn btn-primary float-right" %>
  </div>
</div>
<div class="row">
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row mb-3">
  <div class="col-9">
    <h1><%= @article.title.titleize %></h1>
      <% @article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag), class: "badge badge-secondary" %>
      <% end %>
  </div>
  <div class="col text-right">

    <%= link_to edit_article_path, class: "text-secondary text-decoration-none ml-2" do %>
      <i class="far fa-edit fa-lg"></i>
    <% end %>

    <%= link_to article_path,
          method: :delete,
          data: { confirm: "Are you sure?"},
          class: "text-secondary text-decoration-none ml-2" do %>
            <i class="far fa-trash-alt fa-lg"></i>
    <% end %>
  </div>
</div>
<p class="text-muted"><%= @article.body %></p>

<% if @article.comments.any? %>
  <h3 class="mt-4 mb-4">Comments</h3>
  <div class="list-group">
    <%= render @article.comments %>
  </div>
<% end %>

<h3 class="mt-4 mb-4">Add Comment</h3>
<div class="card">
  <div class="card-body">
    <%= render 'comments/form' %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="list-group-item">
  <strong><%= comment.author %></strong>
  <span class="text-muted"><%= comment.body %></span>
  <%= link_to article_comment_path(comment.article, comment),
        method: :delete,
        data: { confirm: "Are you sure?"},
        class: "text-secondary text-decoration-none ml-2" do %>
          <i class="far fa-trash-alt float-right"></i>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with( model: [ @article, @article.comments.build ], local: true) do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
<div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, class: "form-control" %>
</div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-light mt-5">
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
  <div class="container">
    <%= link_to 'Blogger', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Tags', tags_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body class="bg-light">
    <%= render 'layouts/navbar' %>
    <div class="container mt-5">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>Tags</h1>

<div class="list-group mt-4">
  <% @tags.each do |tag| %>
    <%= link_to tag_path(tag), class: "list-group-item list-group-item-action text-dark text-decoration-none" do %>
      <%= tag.name.titleize %>
      <span class="text-muted small float-right">
        <%= pluralize(tag.articles.count, "article") %>
      </span>
    <% end %>
  <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="row">
  <div class="col-sm-9">
    <h1>Articles tagged with <%= @tag.name %> </h1>
  </div>
  <div class="col-sm-3">
    <%= link_to tag_path, method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="far fa-trash-alt fa-lg text-muted float-right"></i>
    <% end %>

  </div>
</div>



<div class="row mt-4">
  <% @tag.articles.each do |article| %>
    <div class="col-sm-4">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title text-dark">
            <%= article.title %>
          </h5>
          <p class="card-text text-muted">
            <%= article.body.truncate(25) %>
          </p>
          <%= link_to 'Read More', article_path(article), class: "btn btn-outline-secondary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>